# These categories will be applied to all DAGs in the repo.
categories:
  - ETL/ELT
# List of DAGs that should be published to the Astronomer Registry.
dags:
  - path: dags/dbt_cloud/dbt_cloud_operational_check.py
  - path: dags/dbt_cloud/fivetran-dbt_cloud-census.py
  - path: dags/dbt_core/run_from_failure_pattern.py
